const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
const siteRoot = path.resolve(__dirname, '..');
const results = path.join(siteRoot, '.test-results');
const server = http.createServer(async (req,res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url,'http://localhost').pathname);
    const file = path.resolve(siteRoot, '.'+pathname, pathname.endsWith('/') ? 'index.html' : '');
    if (!file.startsWith(siteRoot+path.sep)) return res.writeHead(403).end();
    const body=await fs.readFile(file);
    const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.gif':'image/gif','.png':'image/png'}[path.extname(file)]||'application/octet-stream';
    res.writeHead(200,{'Content-Type':type});res.end(body);
  } catch {res.writeHead(404).end();}
});
let base; let browser;
const courseName = require('node:fs').readFileSync(path.join(siteRoot,'studio/index.html'),'utf8').match(/data-course-name="([^"]+)"/)[1];
let count = 0;
function check(value, label) { assert.ok(value, label); count++; console.log('PASS '+label); }
async function select(page, root, selector='p', start=0, end=null) {
  await page.evaluate(({root,selector,start,end}) => {
    const editor = document.querySelector(root); const el = editor.querySelector(selector);
    const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT); const text=walker.nextNode();
    editor.focus(); const range=document.createRange();
    if (text) { range.setStart(text,start); range.setEnd(text,end ?? text.textContent.length); }
    else { range.selectNodeContents(el); range.collapse(true); }
    const sel=getSelection(); sel.removeAllRanges(); sel.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  },{root,selector,start,end});
}
async function download(page, button, name) {
  const [result] = await Promise.all([page.waitForEvent('download'), page.locator(button).click()]);
  const dest=path.join(results,name); await result.saveAs(dest); return fs.readFile(dest);
}
const image = {name:'example.gif',mimeType:'image/gif',buffer:Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64')};
let videoFixture;
async function addMedia(page, mode, root, opts={}) {
  const toolbar = page.locator(`[data-rich-toolbar="${mode}"]`);
  await select(page,root,'p',0,0);
  await toolbar.locator('[data-action="local"]').click();
  await page.locator('dialog input[type=file]').setInputFiles(opts.video ? videoFixture : opts.pair ? [image,{...image,name:'second.gif'}] : image);
  await page.locator('dialog [name=caption]').fill('Понятная подпись');
  if(opts.pair) await page.locator('dialog [name=columns]').selectOption('2');
  await page.locator('dialog [name=width]').selectOption('75');
  await page.locator('dialog button[type=submit]').click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator(`${root} ${opts.video ? 'video' : '.media-layout[data-columns="'+(opts.pair?'2':'1')+'"] img'}`).first().waitFor();
}
(async()=>{
  await fs.mkdir(results,{recursive:true});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); base='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({ ...(process.platform === 'win32' ? {channel:'msedge'} : {}), headless:true });
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.addInitScript(name => sessionStorage.setItem('studio-auth:'+name,'1'), courseName);
  await context.route('https://fonts.googleapis.com/**',route=>route.fulfill({body:'',contentType:'text/css'}));
  const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/studio/');
  videoFixture = { name:'clip.webm', mimeType:'video/webm', buffer:Buffer.from(await page.evaluate(async()=> {
    const canvas=document.createElement('canvas'); canvas.width=80;canvas.height=40;
    const ctx=canvas.getContext('2d'); const stream=canvas.captureStream(10); const recorder=new MediaRecorder(stream,{mimeType:'video/webm'}); const chunks=[];
    const stopped=new Promise(resolve=>{recorder.onstop=resolve;});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();
    for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#33cc99':'#ff6a3d';ctx.fillRect(0,0,80,40);await new Promise(r=>setTimeout(r,100));}recorder.stop();await stopped;stream.getTracks().forEach(t=>t.stop());
    return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()));
  })) };
  check(await page.locator('#studio').isVisible(),'Studio initializes with restored session');
  check(await page.locator('[data-rich-toolbar]').count()===3,'shared toolbar in all modes');
  await page.locator('#titleInput').fill('Проверка редактора'); await page.locator('#slugInput').fill('editor-test');
  const lecture=page.locator('[data-rich-toolbar=lecture]');
  await page.locator('#editableContent').fill('');
  await page.evaluate(()=> {document.querySelector('#editableContent').innerHTML='<p>Пример текста для форматирования</p><p>Второй абзац</p>'});
  await select(page,'#editableContent','p',0,6);
  await lecture.locator('[data-command=bold]').click();
  check(await page.locator('#editableContent b,#editableContent strong').textContent()==='Пример','bold retains selected text after toolbar click');
  await select(page,'#editableContent','p:nth-child(2)');
  await lecture.locator('[data-style=fontSize]').selectOption('24px');
  check(await page.locator('#editableContent p:nth-child(2) span').evaluate(el=>el.style.fontSize)==='24px','font size applies to content');
  await select(page,'#editableContent','p:nth-child(2)');
  await lecture.locator('[data-style=color]').fill('#33cc99'); await lecture.locator('[data-style=color]').dispatchEvent('change');
  check(await page.locator('#editableContent').evaluate(el=>!!el.querySelector('[style*="rgb(51, 204, 153)"]')),'custom text color');
  await select(page,'#editableContent','p:nth-child(2)');
  await lecture.locator('[data-style=backgroundColor]').fill('#663399'); await lecture.locator('[data-style=backgroundColor]').dispatchEvent('change');
  check(await page.locator('#editableContent').evaluate(el=>!!el.querySelector('[style*="background-color"]')),'custom highlight');
  await select(page,'#editableContent','p:nth-child(2)');
  await lecture.locator('[data-style=fontFamily]').selectOption('PT Serif');
  check(await page.locator('#editableContent [data-course-font="PT Serif"]').count()>0,'inline Google font retained as metadata');
  check(await page.locator('#editableContent [data-course-font="PT Serif"]').evaluate(el=>el.style.fontSize==='24px' && el.style.color==='rgb(51, 204, 153)' && el.style.backgroundColor==='rgb(102, 51, 153)'),'successive styles retain size, color and highlight');
  await select(page,'#editableContent','p:nth-child(2)');
  await lecture.locator('[data-action=link]').click(); await page.locator('dialog [name=url]').fill('https://example.com/course'); await page.locator('dialog button[type=submit]').click();
  check(await page.locator('#editableContent a[href="https://example.com/course"]').count()===1,'link on selected text');
  await select(page,'#editableContent','p',0,0);
  await lecture.locator('[data-action=code]').click();
  const code='const value = "<div>& literal";\n  console.log(value);';
  await page.locator('dialog [name=language]').fill('JavaScript'); await page.locator('dialog [name=code]').fill(code); await page.locator('dialog button[type=submit]').click();
  check(await page.locator('pre.course-code code').textContent()===code,'code preserves literal markup and whitespace');
  await addMedia(page,'lecture','#editableContent',{pair:true});
  check(await page.locator('#editableContent .media-layout[data-columns="2"] img').count()===2,'two GIF images side by side');
  check(await page.locator('#editableContent .media-layout').evaluate(el=>el.style.width)==='75%','media width');
  await page.locator('#editableContent figure').first().click();
  await page.locator('[data-media-caption]').fill('Обновлённая подпись'); await page.locator('[data-media-width]').fill('50');
  check(await page.locator('#editableContent figcaption').first().textContent()==='Обновлённая подпись','caption inspector');
  await addMedia(page,'lecture','#editableContent',{video:true});
  check(await page.locator('#editableContent video[controls]').count()===1,'own video player');
  await page.waitForFunction(()=>document.querySelector('#editableContent video')?.readyState>=1);
  check(await page.locator('#editableContent video').evaluate(el=>el.videoWidth===80),'uploaded WebM decodes in browser');
  const html=(await download(page,'#downloadLecture','lecture.html')).toString();
  check(!html.includes('blob:')&&!html.includes('contenteditable')&&!html.includes('data-studio-asset'),'export removes editor state and blob URLs');
  check(html.includes('assets/videos/')&&html.includes('data-columns="2"')&&html.includes('PT Serif')&&html.includes('24px'),'lecture export retains media and typography');
  check(!/<p[^>]*>\s*<(figure|div class="media-layout"|pre)/.test(html),'media/code are not nested in paragraphs');
  const zip=await download(page,'#downloadPackage','lecture.zip');
  check(zip.includes(Buffer.from('assets/videos/'))&&zip.includes(Buffer.from('example.gif')),'lecture ZIP includes files');
  await page.locator('#editableContent').dispatchEvent('input');
  await page.waitForTimeout(800);
  await page.reload();
  check(await page.locator('#slugInput').inputValue()==='editor-test','last lecture draft restored on reload');
  await page.waitForFunction(()=>document.querySelector('#editableContent img')?.src.startsWith('blob:'));
  check(await page.locator('#editableContent img').first().evaluate(img=>img.naturalWidth)>0,'GIF restored from IndexedDB after reload');
  // Main page: media paths must be relative to the site root.
  await page.locator('[data-editor-mode=home]').click(); await page.waitForFunction(()=>document.querySelector('#homeAboutEditable p'));
  await addMedia(page,'home','#homeAboutEditable',{pair:true});
  const home=(await download(page,'#downloadHome','home.html')).toString();
  check(home.includes('src="assets/images/')&&!home.includes('blob:'),'home media uses root-relative export paths');
  const homeZip=await download(page,'#downloadHomePackage','home.zip');
  check(homeZip.includes(Buffer.from('assets/images/'))&&homeZip.includes(Buffer.from('index.html')),'home ZIP packages media');
  await select(page,'#homeAboutEditable','p',0,0); await page.locator('[data-rich-toolbar=home] [data-action=url]').click();
  await page.locator('dialog [name=kind]').selectOption('embed'); await page.locator('dialog [name=url]').fill('https://youtu.be/dQw4w9WgXcQ'); await page.locator('dialog [name=caption]').fill('Видео с пояснением'); await page.locator('dialog button[type=submit]').click();
  check(await page.locator('#homeAboutEditable iframe').getAttribute('src')==='https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ','YouTube embed in home page');
  await page.locator('[data-editor-mode=resource]').click(); await page.waitForFunction(()=>document.querySelector('#resourceEditable p'));
  await addMedia(page,'resource','#resourceEditable',{pair:true});
  const resource=(await download(page,'#downloadResource','resource.html')).toString();
  check(resource.includes('class="media-layout"')&&resource.includes('src="../assets/images/'),'resource media survives normalization');
  const resourceZip=await download(page,'#downloadResourcePackage','resource.zip'); check(resourceZip.includes(Buffer.from('assets/images/')),'resource ZIP packages images');
  await page.locator('#resourceEditable').dispatchEvent('input'); await page.waitForTimeout(800);
  await page.locator('[data-editor-mode=home]').click(); await page.locator('#homeAboutEditable').dispatchEvent('input'); await page.waitForTimeout(800);
  await page.reload(); await page.locator('[data-editor-mode=home]').click();
  await page.waitForFunction(()=>document.querySelector('#homeAboutEditable img')?.src.startsWith('blob:'));
  check(await page.locator('#homeAboutEditable img').count()===2,'home media draft restored');
  await page.locator('[data-editor-mode=resource]').click(); await page.waitForFunction(()=>document.querySelector('#resourceEditable img')?.src.startsWith('blob:'));
  check(await page.locator('#resourceEditable img').count()===2,'resource media draft restored');
  // A collapsed selection styles the paragraph, never the unsaved editing root.
  await select(page,'#resourceEditable','p',0,0); await page.locator('[data-rich-toolbar=resource] [data-style=fontSize]').selectOption('32px');
  check(await page.locator('#resourceEditable').evaluate(el=>!el.style.fontSize && [...el.querySelectorAll('p')].some(p=>p.style.fontSize==='32px')),'collapsed selection font size survives export');
  await page.locator('#siteFont').fill('Noto Sans'); await page.locator('#siteFont').dispatchEvent('change');
  check(await page.evaluate(()=>getComputedStyle(document.body).fontFamily.includes('Noto Sans')),'site font preview');
  const settings=(await download(page,'#downloadSiteFont','site-settings.js')).toString(); check(settings.includes('Noto Sans'),'global font settings export');
  // Mock GitHub to exercise upload ordering without changing remote pages.
  const writes=[]; await context.route('https://api.github.com/**',async route=>{
    const req=route.request();
    if(req.method()==='PUT') {writes.push({url:req.url(),data:JSON.parse(req.postData())}); await route.fulfill({status:200,body:'{}',contentType:'application/json'});}
    else await route.fulfill({status:404,body:'{}',contentType:'application/json'});
  });
  await page.locator('#githubSettings').evaluate(el=>el.open=true);
  await page.locator('#githubOwner').fill('test');await page.locator('#githubRepo').fill('course');await page.locator('#githubToken').fill('fake-test-token');
  await page.locator('#publishResource').click(); await page.waitForFunction(()=>document.querySelector('#editorStatus').textContent.includes('опубликована'));
  check(writes.length===3&&writes[0].url.includes('assets/images/')&&writes[2].url.includes('resources/lists.html'),'publish media before referencing HTML');
  const posted=Buffer.from(writes[2].data.content,'base64').toString(); check(!posted.includes('blob:')&&posted.includes('media-layout'),'published payload is clean');
  await page.screenshot({path:path.join(results,'studio-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile Studio has no horizontal overflow');
  await page.screenshot({path:path.join(results,'studio-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-editor-mode=lecture]').click();
  const slugs = await page.evaluate(()=>window.COURSE_TOPICS.slice(0,2).map(topic=>topic.slug));
  await page.locator('#topicSelect').selectOption(slugs[0]);
  await page.locator('#loadPublished').click();
  await page.waitForFunction(()=>document.querySelector('#editorStatus').textContent.includes('лекция загружена'));
  const originalBody = await page.locator('#editableContent').innerHTML();
  await page.locator('#topicThumbnailFile').setInputFiles({...image,name:'topic-cover.gif'});
  await page.waitForFunction(()=>document.querySelector('#topicThumbnailPreview img')?.naturalWidth>0);
  check(await page.locator('#editableContent').innerHTML()===originalBody,'thumbnail upload never inserts image in lecture content');
  let topicsText=(await download(page,'#downloadTopics','topics-with-thumbnail.js')).toString();
  const parseTopics=text=>JSON.parse(text.replace(/^window\.COURSE_TOPICS\s*=\s*/,'').replace(/;\s*$/,''));
  let records=parseTopics(topicsText); const coverPath=records.find(t=>t.slug===slugs[0]).thumbnail;
  check(coverPath.startsWith('assets/images/')&&!coverPath.includes('blob:'),'thumbnail metadata uses permanent site path');
  const lectureWithCover=(await download(page,'#downloadLecture','lecture-with-cover.html')).toString();
  check(!lectureWithCover.includes(coverPath),'exported lecture contains no cover image');
  await page.locator('#topicSelect').selectOption(slugs[1]);
  check(await page.locator('#topicThumbnailPreview img').count()===0,'different topic has independent thumbnail');
  await page.locator('#topicThumbnailFile').setInputFiles({...image,name:'second-cover.gif'});
  await page.waitForFunction(()=>document.querySelector('#topicThumbnailPreview img')?.naturalWidth>0);
  await page.locator('#topicSelect').selectOption(slugs[0]);
  await page.waitForFunction(()=>document.querySelector('#topicThumbnailPreview img')?.naturalWidth>0);
  check(await page.locator('#topicThumbnailPreview img').count()===1,'thumbnail restored when switching topics');
  await page.waitForTimeout(800); await page.reload();
  await page.waitForFunction(()=>document.querySelector('#topicThumbnailPreview img')?.naturalWidth>0);
  check(await page.locator('#slugInput').inputValue()===slugs[0],'thumbnail and selected topic restored after reload');
  topicsText=(await download(page,'#downloadTopics','topics-with-two-thumbnails.js')).toString();
  records=parseTopics(topicsText);
  check(records.filter(t=>t.thumbnail).length===2,'both topic covers persist in topics list');
  const coversZip=await download(page,'#downloadThumbnailPackage','topic-thumbnails.zip');
  check(coversZip.includes(Buffer.from('topics.js'))&&coversZip.includes(Buffer.from('topic-cover.gif'))&&coversZip.includes(Buffer.from('second-cover.gif')),'thumbnail ZIP contains registry and both covers');
  const fullLectureZip=await download(page,'#downloadPackage','lecture-with-thumbnail.zip');
  check(fullLectureZip.includes(Buffer.from('topic-cover.gif')),'regular lecture ZIP includes topic covers');
  await page.locator('#githubSettings').evaluate(el=>el.open=true);
  writes.length=0; await page.locator('#publishTopicThumbnail').click();
  await page.waitForFunction(()=>document.querySelector('#editorStatus').textContent.includes('Превью опубликованы'));
  check(writes.length===3&&writes.at(-1).url.includes('topics.js')&&writes.slice(0,2).every(w=>w.url.includes('assets/images/')),'thumbnail publication uploads covers before registry');
  check(!writes.some(w=>w.url.includes('lectures/')),'thumbnail publication never rewrites lecture HTML');
  const sitePage=await context.newPage();
  await context.route('**/topics.js*',route=>route.fulfill({body:topicsText,contentType:'text/javascript'}));
  await context.route('**/'+coverPath,route=>route.fulfill({body:image.buffer,contentType:image.mimeType}));
  await sitePage.goto(base+'/index.html');
  const card=sitePage.locator(`.topic[href="lectures/${slugs[0]}.html"] .thumb`);
  await card.scrollIntoViewIfNeeded();
  await sitePage.waitForFunction(slug=>document.querySelector(`.topic[href="lectures/${slug}.html"] .thumb img`)?.naturalWidth>0,slugs[0]);
  check(await card.locator('img').getAttribute('src')===coverPath,'home page renders uploaded thumbnail');
  check(await card.locator('img').evaluate(el=>getComputedStyle(el).objectFit)==='cover','thumbnail fits existing card design');
  check(await card.evaluate(el=>getComputedStyle(el,'::before').display)==='none','decorative shapes are hidden only for custom thumbnails');
  await sitePage.goto(base+'/lectures/'+slugs[0]+'.html');
  check(await sitePage.locator('.lecture-article img').evaluateAll((images,path)=>images.every(img=>!img.src.endsWith(path)),coverPath),'published lecture article has no thumbnail');
  await page.locator('#removeTopicThumbnail').click();
  check(await page.locator('#topicThumbnailPreview img').count()===0,'remove restores default thumbnail');
  topicsText=(await download(page,'#downloadTopics','topics-with-cover-removed.js')).toString();
  check(!parseTopics(topicsText).find(t=>t.slug===slugs[0]).thumbnail,'removed cover is omitted from exported metadata');
  await sitePage.goto(base+'/index.html');
  check(await sitePage.locator(`.topic[href="lectures/${slugs[0]}.html"] .thumb:not(.has-thumbnail)`).count()===1,'home page restores original decorative preview after removal');
  await sitePage.close();
  check(errors.length===0,'no browser JavaScript errors: '+errors.join('; '));
  await browser.close(); await new Promise(resolve=>server.close(resolve)); console.log('TOTAL '+count+' checks passed');
})().catch(async e=>{console.error(e);if(browser)await browser.close();server.close();process.exitCode=1});
